### ISSUE TITLE
Not working properly?

### ISSUE THREAD

**Issue by xJon** [Glease/Healer#1]
Not sure if I'm using this wrong or not, but I've downloaded `Healer-1.1.0.jar` from `Releases` and tried to put it in `mods` or in `mods\1.7.10`.
In both cases, running `${date:YYYY}` on singleplayer prints `2021` onto the game log which is not supposed to happen.
Any idea what's going wrong?
Thanks!

**Comment by Glease** [comment]
Try jndi something instead. This mod does not remove all lookups. Only JNDI is removed.

**Comment by xJon** [comment]
I'm actually not sure how to test that but thank you for the response. Why not disable all lookups?

**Comment by Glease** [comment]
Sure I can clear the lookup map, but it will not help speed up the logging in any way. (Log4j will still attempt to search for `${`, and if there is any, it will still step into the Interpolator code and do regex matching) That can only be achieved by using another log4j jar (this is what peterix is doing with MultiMC, as with many other launchers) Since there is no gain, I didn't bother to clear the lookup map.

**Comment by xJon** [comment]
Thanks for the detailed response!
