### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Moonyol** [Glease/Healer#3]
Crash with https://modrinth.com/mod/pipeblocker, https://pastebin.com/NBA3twKg
https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/issues/22

forge 14.23.5.2859 1.12.2 Windows 10
![image](https://github.com/Glease/Healer/assets/92951072/231e5ee6-6094-42fe-9d53-e8c47bcafdf2)

**Comment by Glease** [comment]
pipeblocker issue. not healer related. also as a hint try use a more recent build of java8 instead of whatever the cursed curse launcher installed for you, e.g. [one](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html) [of](https://adoptium.net/temurin/releases/?version=8&os=windows&arch=x64&package=jre) [these](https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre#zulu)
